// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: endpoint.proto

package iroha.protocol;

public final class Endpoint {
  private Endpoint() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code iroha.protocol.TxStatus}
   */
  public enum TxStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>STATELESS_VALIDATION_FAILED = 0;</code>
     */
    STATELESS_VALIDATION_FAILED(0),
    /**
     * <code>STATELESS_VALIDATION_SUCCESS = 1;</code>
     */
    STATELESS_VALIDATION_SUCCESS(1),
    /**
     * <code>STATEFUL_VALIDATION_FAILED = 2;</code>
     */
    STATEFUL_VALIDATION_FAILED(2),
    /**
     * <code>STATEFUL_VALIDATION_SUCCESS = 3;</code>
     */
    STATEFUL_VALIDATION_SUCCESS(3),
    /**
     * <code>REJECTED = 4;</code>
     */
    REJECTED(4),
    /**
     * <code>COMMITTED = 5;</code>
     */
    COMMITTED(5),
    /**
     * <code>MST_EXPIRED = 6;</code>
     */
    MST_EXPIRED(6),
    /**
     * <code>NOT_RECEIVED = 7;</code>
     */
    NOT_RECEIVED(7),
    /**
     * <code>MST_PENDING = 8;</code>
     */
    MST_PENDING(8),
    /**
     * <code>ENOUGH_SIGNATURES_COLLECTED = 9;</code>
     */
    ENOUGH_SIGNATURES_COLLECTED(9),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>STATELESS_VALIDATION_FAILED = 0;</code>
     */
    public static final int STATELESS_VALIDATION_FAILED_VALUE = 0;
    /**
     * <code>STATELESS_VALIDATION_SUCCESS = 1;</code>
     */
    public static final int STATELESS_VALIDATION_SUCCESS_VALUE = 1;
    /**
     * <code>STATEFUL_VALIDATION_FAILED = 2;</code>
     */
    public static final int STATEFUL_VALIDATION_FAILED_VALUE = 2;
    /**
     * <code>STATEFUL_VALIDATION_SUCCESS = 3;</code>
     */
    public static final int STATEFUL_VALIDATION_SUCCESS_VALUE = 3;
    /**
     * <code>REJECTED = 4;</code>
     */
    public static final int REJECTED_VALUE = 4;
    /**
     * <code>COMMITTED = 5;</code>
     */
    public static final int COMMITTED_VALUE = 5;
    /**
     * <code>MST_EXPIRED = 6;</code>
     */
    public static final int MST_EXPIRED_VALUE = 6;
    /**
     * <code>NOT_RECEIVED = 7;</code>
     */
    public static final int NOT_RECEIVED_VALUE = 7;
    /**
     * <code>MST_PENDING = 8;</code>
     */
    public static final int MST_PENDING_VALUE = 8;
    /**
     * <code>ENOUGH_SIGNATURES_COLLECTED = 9;</code>
     */
    public static final int ENOUGH_SIGNATURES_COLLECTED_VALUE = 9;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TxStatus valueOf(int value) {
      return forNumber(value);
    }

    public static TxStatus forNumber(int value) {
      switch (value) {
        case 0: return STATELESS_VALIDATION_FAILED;
        case 1: return STATELESS_VALIDATION_SUCCESS;
        case 2: return STATEFUL_VALIDATION_FAILED;
        case 3: return STATEFUL_VALIDATION_SUCCESS;
        case 4: return REJECTED;
        case 5: return COMMITTED;
        case 6: return MST_EXPIRED;
        case 7: return NOT_RECEIVED;
        case 8: return MST_PENDING;
        case 9: return ENOUGH_SIGNATURES_COLLECTED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TxStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TxStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TxStatus>() {
            public TxStatus findValueByNumber(int number) {
              return TxStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return iroha.protocol.Endpoint.getDescriptor().getEnumTypes().get(0);
    }

    private static final TxStatus[] VALUES = values();

    public static TxStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TxStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:iroha.protocol.TxStatus)
  }

  public interface ToriiResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:iroha.protocol.ToriiResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.iroha.protocol.TxStatus tx_status = 1;</code>
     */
    int getTxStatusValue();
    /**
     * <code>.iroha.protocol.TxStatus tx_status = 1;</code>
     */
    iroha.protocol.Endpoint.TxStatus getTxStatus();

    /**
     * <code>string tx_hash = 2;</code>
     */
    java.lang.String getTxHash();
    /**
     * <code>string tx_hash = 2;</code>
     */
    com.google.protobuf.ByteString
        getTxHashBytes();

    /**
     * <code>string err_or_cmd_name = 3;</code>
     */
    java.lang.String getErrOrCmdName();
    /**
     * <code>string err_or_cmd_name = 3;</code>
     */
    com.google.protobuf.ByteString
        getErrOrCmdNameBytes();

    /**
     * <code>uint64 failed_cmd_index = 4;</code>
     */
    long getFailedCmdIndex();

    /**
     * <code>uint32 error_code = 5;</code>
     */
    int getErrorCode();
  }
  /**
   * Protobuf type {@code iroha.protocol.ToriiResponse}
   */
  public  static final class ToriiResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:iroha.protocol.ToriiResponse)
      ToriiResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ToriiResponse.newBuilder() to construct.
    private ToriiResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ToriiResponse() {
      txStatus_ = 0;
      txHash_ = "";
      errOrCmdName_ = "";
      failedCmdIndex_ = 0L;
      errorCode_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ToriiResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              txStatus_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              txHash_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              errOrCmdName_ = s;
              break;
            }
            case 32: {

              failedCmdIndex_ = input.readUInt64();
              break;
            }
            case 40: {

              errorCode_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return iroha.protocol.Endpoint.internal_static_iroha_protocol_ToriiResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return iroha.protocol.Endpoint.internal_static_iroha_protocol_ToriiResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              iroha.protocol.Endpoint.ToriiResponse.class, iroha.protocol.Endpoint.ToriiResponse.Builder.class);
    }

    public static final int TX_STATUS_FIELD_NUMBER = 1;
    private int txStatus_;
    /**
     * <code>.iroha.protocol.TxStatus tx_status = 1;</code>
     */
    public int getTxStatusValue() {
      return txStatus_;
    }
    /**
     * <code>.iroha.protocol.TxStatus tx_status = 1;</code>
     */
    public iroha.protocol.Endpoint.TxStatus getTxStatus() {
      iroha.protocol.Endpoint.TxStatus result = iroha.protocol.Endpoint.TxStatus.valueOf(txStatus_);
      return result == null ? iroha.protocol.Endpoint.TxStatus.UNRECOGNIZED : result;
    }

    public static final int TX_HASH_FIELD_NUMBER = 2;
    private volatile java.lang.Object txHash_;
    /**
     * <code>string tx_hash = 2;</code>
     */
    public java.lang.String getTxHash() {
      java.lang.Object ref = txHash_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        txHash_ = s;
        return s;
      }
    }
    /**
     * <code>string tx_hash = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTxHashBytes() {
      java.lang.Object ref = txHash_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        txHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERR_OR_CMD_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object errOrCmdName_;
    /**
     * <code>string err_or_cmd_name = 3;</code>
     */
    public java.lang.String getErrOrCmdName() {
      java.lang.Object ref = errOrCmdName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errOrCmdName_ = s;
        return s;
      }
    }
    /**
     * <code>string err_or_cmd_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getErrOrCmdNameBytes() {
      java.lang.Object ref = errOrCmdName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errOrCmdName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FAILED_CMD_INDEX_FIELD_NUMBER = 4;
    private long failedCmdIndex_;
    /**
     * <code>uint64 failed_cmd_index = 4;</code>
     */
    public long getFailedCmdIndex() {
      return failedCmdIndex_;
    }

    public static final int ERROR_CODE_FIELD_NUMBER = 5;
    private int errorCode_;
    /**
     * <code>uint32 error_code = 5;</code>
     */
    public int getErrorCode() {
      return errorCode_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (txStatus_ != iroha.protocol.Endpoint.TxStatus.STATELESS_VALIDATION_FAILED.getNumber()) {
        output.writeEnum(1, txStatus_);
      }
      if (!getTxHashBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, txHash_);
      }
      if (!getErrOrCmdNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errOrCmdName_);
      }
      if (failedCmdIndex_ != 0L) {
        output.writeUInt64(4, failedCmdIndex_);
      }
      if (errorCode_ != 0) {
        output.writeUInt32(5, errorCode_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (txStatus_ != iroha.protocol.Endpoint.TxStatus.STATELESS_VALIDATION_FAILED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, txStatus_);
      }
      if (!getTxHashBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, txHash_);
      }
      if (!getErrOrCmdNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, errOrCmdName_);
      }
      if (failedCmdIndex_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, failedCmdIndex_);
      }
      if (errorCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, errorCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof iroha.protocol.Endpoint.ToriiResponse)) {
        return super.equals(obj);
      }
      iroha.protocol.Endpoint.ToriiResponse other = (iroha.protocol.Endpoint.ToriiResponse) obj;

      boolean result = true;
      result = result && txStatus_ == other.txStatus_;
      result = result && getTxHash()
          .equals(other.getTxHash());
      result = result && getErrOrCmdName()
          .equals(other.getErrOrCmdName());
      result = result && (getFailedCmdIndex()
          == other.getFailedCmdIndex());
      result = result && (getErrorCode()
          == other.getErrorCode());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TX_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + txStatus_;
      hash = (37 * hash) + TX_HASH_FIELD_NUMBER;
      hash = (53 * hash) + getTxHash().hashCode();
      hash = (37 * hash) + ERR_OR_CMD_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getErrOrCmdName().hashCode();
      hash = (37 * hash) + FAILED_CMD_INDEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFailedCmdIndex());
      hash = (37 * hash) + ERROR_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static iroha.protocol.Endpoint.ToriiResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static iroha.protocol.Endpoint.ToriiResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static iroha.protocol.Endpoint.ToriiResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static iroha.protocol.Endpoint.ToriiResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static iroha.protocol.Endpoint.ToriiResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static iroha.protocol.Endpoint.ToriiResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static iroha.protocol.Endpoint.ToriiResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static iroha.protocol.Endpoint.ToriiResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static iroha.protocol.Endpoint.ToriiResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static iroha.protocol.Endpoint.ToriiResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static iroha.protocol.Endpoint.ToriiResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static iroha.protocol.Endpoint.ToriiResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(iroha.protocol.Endpoint.ToriiResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code iroha.protocol.ToriiResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:iroha.protocol.ToriiResponse)
        iroha.protocol.Endpoint.ToriiResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return iroha.protocol.Endpoint.internal_static_iroha_protocol_ToriiResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return iroha.protocol.Endpoint.internal_static_iroha_protocol_ToriiResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                iroha.protocol.Endpoint.ToriiResponse.class, iroha.protocol.Endpoint.ToriiResponse.Builder.class);
      }

      // Construct using iroha.protocol.Endpoint.ToriiResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        txStatus_ = 0;

        txHash_ = "";

        errOrCmdName_ = "";

        failedCmdIndex_ = 0L;

        errorCode_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return iroha.protocol.Endpoint.internal_static_iroha_protocol_ToriiResponse_descriptor;
      }

      public iroha.protocol.Endpoint.ToriiResponse getDefaultInstanceForType() {
        return iroha.protocol.Endpoint.ToriiResponse.getDefaultInstance();
      }

      public iroha.protocol.Endpoint.ToriiResponse build() {
        iroha.protocol.Endpoint.ToriiResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public iroha.protocol.Endpoint.ToriiResponse buildPartial() {
        iroha.protocol.Endpoint.ToriiResponse result = new iroha.protocol.Endpoint.ToriiResponse(this);
        result.txStatus_ = txStatus_;
        result.txHash_ = txHash_;
        result.errOrCmdName_ = errOrCmdName_;
        result.failedCmdIndex_ = failedCmdIndex_;
        result.errorCode_ = errorCode_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof iroha.protocol.Endpoint.ToriiResponse) {
          return mergeFrom((iroha.protocol.Endpoint.ToriiResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(iroha.protocol.Endpoint.ToriiResponse other) {
        if (other == iroha.protocol.Endpoint.ToriiResponse.getDefaultInstance()) return this;
        if (other.txStatus_ != 0) {
          setTxStatusValue(other.getTxStatusValue());
        }
        if (!other.getTxHash().isEmpty()) {
          txHash_ = other.txHash_;
          onChanged();
        }
        if (!other.getErrOrCmdName().isEmpty()) {
          errOrCmdName_ = other.errOrCmdName_;
          onChanged();
        }
        if (other.getFailedCmdIndex() != 0L) {
          setFailedCmdIndex(other.getFailedCmdIndex());
        }
        if (other.getErrorCode() != 0) {
          setErrorCode(other.getErrorCode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        iroha.protocol.Endpoint.ToriiResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (iroha.protocol.Endpoint.ToriiResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int txStatus_ = 0;
      /**
       * <code>.iroha.protocol.TxStatus tx_status = 1;</code>
       */
      public int getTxStatusValue() {
        return txStatus_;
      }
      /**
       * <code>.iroha.protocol.TxStatus tx_status = 1;</code>
       */
      public Builder setTxStatusValue(int value) {
        txStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.iroha.protocol.TxStatus tx_status = 1;</code>
       */
      public iroha.protocol.Endpoint.TxStatus getTxStatus() {
        iroha.protocol.Endpoint.TxStatus result = iroha.protocol.Endpoint.TxStatus.valueOf(txStatus_);
        return result == null ? iroha.protocol.Endpoint.TxStatus.UNRECOGNIZED : result;
      }
      /**
       * <code>.iroha.protocol.TxStatus tx_status = 1;</code>
       */
      public Builder setTxStatus(iroha.protocol.Endpoint.TxStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        txStatus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.iroha.protocol.TxStatus tx_status = 1;</code>
       */
      public Builder clearTxStatus() {
        
        txStatus_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object txHash_ = "";
      /**
       * <code>string tx_hash = 2;</code>
       */
      public java.lang.String getTxHash() {
        java.lang.Object ref = txHash_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          txHash_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tx_hash = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTxHashBytes() {
        java.lang.Object ref = txHash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          txHash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tx_hash = 2;</code>
       */
      public Builder setTxHash(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        txHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tx_hash = 2;</code>
       */
      public Builder clearTxHash() {
        
        txHash_ = getDefaultInstance().getTxHash();
        onChanged();
        return this;
      }
      /**
       * <code>string tx_hash = 2;</code>
       */
      public Builder setTxHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        txHash_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object errOrCmdName_ = "";
      /**
       * <code>string err_or_cmd_name = 3;</code>
       */
      public java.lang.String getErrOrCmdName() {
        java.lang.Object ref = errOrCmdName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errOrCmdName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string err_or_cmd_name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getErrOrCmdNameBytes() {
        java.lang.Object ref = errOrCmdName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errOrCmdName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string err_or_cmd_name = 3;</code>
       */
      public Builder setErrOrCmdName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errOrCmdName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string err_or_cmd_name = 3;</code>
       */
      public Builder clearErrOrCmdName() {
        
        errOrCmdName_ = getDefaultInstance().getErrOrCmdName();
        onChanged();
        return this;
      }
      /**
       * <code>string err_or_cmd_name = 3;</code>
       */
      public Builder setErrOrCmdNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errOrCmdName_ = value;
        onChanged();
        return this;
      }

      private long failedCmdIndex_ ;
      /**
       * <code>uint64 failed_cmd_index = 4;</code>
       */
      public long getFailedCmdIndex() {
        return failedCmdIndex_;
      }
      /**
       * <code>uint64 failed_cmd_index = 4;</code>
       */
      public Builder setFailedCmdIndex(long value) {
        
        failedCmdIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 failed_cmd_index = 4;</code>
       */
      public Builder clearFailedCmdIndex() {
        
        failedCmdIndex_ = 0L;
        onChanged();
        return this;
      }

      private int errorCode_ ;
      /**
       * <code>uint32 error_code = 5;</code>
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>uint32 error_code = 5;</code>
       */
      public Builder setErrorCode(int value) {
        
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 error_code = 5;</code>
       */
      public Builder clearErrorCode() {
        
        errorCode_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:iroha.protocol.ToriiResponse)
    }

    // @@protoc_insertion_point(class_scope:iroha.protocol.ToriiResponse)
    private static final iroha.protocol.Endpoint.ToriiResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new iroha.protocol.Endpoint.ToriiResponse();
    }

    public static iroha.protocol.Endpoint.ToriiResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ToriiResponse>
        PARSER = new com.google.protobuf.AbstractParser<ToriiResponse>() {
      public ToriiResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ToriiResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ToriiResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ToriiResponse> getParserForType() {
      return PARSER;
    }

    public iroha.protocol.Endpoint.ToriiResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TxStatusRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:iroha.protocol.TxStatusRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string tx_hash = 1;</code>
     */
    java.lang.String getTxHash();
    /**
     * <code>string tx_hash = 1;</code>
     */
    com.google.protobuf.ByteString
        getTxHashBytes();
  }
  /**
   * Protobuf type {@code iroha.protocol.TxStatusRequest}
   */
  public  static final class TxStatusRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:iroha.protocol.TxStatusRequest)
      TxStatusRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TxStatusRequest.newBuilder() to construct.
    private TxStatusRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TxStatusRequest() {
      txHash_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TxStatusRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              txHash_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return iroha.protocol.Endpoint.internal_static_iroha_protocol_TxStatusRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return iroha.protocol.Endpoint.internal_static_iroha_protocol_TxStatusRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              iroha.protocol.Endpoint.TxStatusRequest.class, iroha.protocol.Endpoint.TxStatusRequest.Builder.class);
    }

    public static final int TX_HASH_FIELD_NUMBER = 1;
    private volatile java.lang.Object txHash_;
    /**
     * <code>string tx_hash = 1;</code>
     */
    public java.lang.String getTxHash() {
      java.lang.Object ref = txHash_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        txHash_ = s;
        return s;
      }
    }
    /**
     * <code>string tx_hash = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTxHashBytes() {
      java.lang.Object ref = txHash_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        txHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTxHashBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, txHash_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTxHashBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, txHash_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof iroha.protocol.Endpoint.TxStatusRequest)) {
        return super.equals(obj);
      }
      iroha.protocol.Endpoint.TxStatusRequest other = (iroha.protocol.Endpoint.TxStatusRequest) obj;

      boolean result = true;
      result = result && getTxHash()
          .equals(other.getTxHash());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TX_HASH_FIELD_NUMBER;
      hash = (53 * hash) + getTxHash().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static iroha.protocol.Endpoint.TxStatusRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static iroha.protocol.Endpoint.TxStatusRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static iroha.protocol.Endpoint.TxStatusRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static iroha.protocol.Endpoint.TxStatusRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static iroha.protocol.Endpoint.TxStatusRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static iroha.protocol.Endpoint.TxStatusRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static iroha.protocol.Endpoint.TxStatusRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static iroha.protocol.Endpoint.TxStatusRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static iroha.protocol.Endpoint.TxStatusRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static iroha.protocol.Endpoint.TxStatusRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static iroha.protocol.Endpoint.TxStatusRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static iroha.protocol.Endpoint.TxStatusRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(iroha.protocol.Endpoint.TxStatusRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code iroha.protocol.TxStatusRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:iroha.protocol.TxStatusRequest)
        iroha.protocol.Endpoint.TxStatusRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return iroha.protocol.Endpoint.internal_static_iroha_protocol_TxStatusRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return iroha.protocol.Endpoint.internal_static_iroha_protocol_TxStatusRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                iroha.protocol.Endpoint.TxStatusRequest.class, iroha.protocol.Endpoint.TxStatusRequest.Builder.class);
      }

      // Construct using iroha.protocol.Endpoint.TxStatusRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        txHash_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return iroha.protocol.Endpoint.internal_static_iroha_protocol_TxStatusRequest_descriptor;
      }

      public iroha.protocol.Endpoint.TxStatusRequest getDefaultInstanceForType() {
        return iroha.protocol.Endpoint.TxStatusRequest.getDefaultInstance();
      }

      public iroha.protocol.Endpoint.TxStatusRequest build() {
        iroha.protocol.Endpoint.TxStatusRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public iroha.protocol.Endpoint.TxStatusRequest buildPartial() {
        iroha.protocol.Endpoint.TxStatusRequest result = new iroha.protocol.Endpoint.TxStatusRequest(this);
        result.txHash_ = txHash_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof iroha.protocol.Endpoint.TxStatusRequest) {
          return mergeFrom((iroha.protocol.Endpoint.TxStatusRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(iroha.protocol.Endpoint.TxStatusRequest other) {
        if (other == iroha.protocol.Endpoint.TxStatusRequest.getDefaultInstance()) return this;
        if (!other.getTxHash().isEmpty()) {
          txHash_ = other.txHash_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        iroha.protocol.Endpoint.TxStatusRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (iroha.protocol.Endpoint.TxStatusRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object txHash_ = "";
      /**
       * <code>string tx_hash = 1;</code>
       */
      public java.lang.String getTxHash() {
        java.lang.Object ref = txHash_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          txHash_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tx_hash = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTxHashBytes() {
        java.lang.Object ref = txHash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          txHash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tx_hash = 1;</code>
       */
      public Builder setTxHash(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        txHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tx_hash = 1;</code>
       */
      public Builder clearTxHash() {
        
        txHash_ = getDefaultInstance().getTxHash();
        onChanged();
        return this;
      }
      /**
       * <code>string tx_hash = 1;</code>
       */
      public Builder setTxHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        txHash_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:iroha.protocol.TxStatusRequest)
    }

    // @@protoc_insertion_point(class_scope:iroha.protocol.TxStatusRequest)
    private static final iroha.protocol.Endpoint.TxStatusRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new iroha.protocol.Endpoint.TxStatusRequest();
    }

    public static iroha.protocol.Endpoint.TxStatusRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TxStatusRequest>
        PARSER = new com.google.protobuf.AbstractParser<TxStatusRequest>() {
      public TxStatusRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TxStatusRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TxStatusRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TxStatusRequest> getParserForType() {
      return PARSER;
    }

    public iroha.protocol.Endpoint.TxStatusRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TxListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:iroha.protocol.TxList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
     */
    java.util.List<iroha.protocol.TransactionOuterClass.Transaction> 
        getTransactionsList();
    /**
     * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
     */
    iroha.protocol.TransactionOuterClass.Transaction getTransactions(int index);
    /**
     * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
     */
    int getTransactionsCount();
    /**
     * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
     */
    java.util.List<? extends iroha.protocol.TransactionOuterClass.TransactionOrBuilder> 
        getTransactionsOrBuilderList();
    /**
     * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
     */
    iroha.protocol.TransactionOuterClass.TransactionOrBuilder getTransactionsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code iroha.protocol.TxList}
   */
  public  static final class TxList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:iroha.protocol.TxList)
      TxListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TxList.newBuilder() to construct.
    private TxList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TxList() {
      transactions_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TxList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                transactions_ = new java.util.ArrayList<iroha.protocol.TransactionOuterClass.Transaction>();
                mutable_bitField0_ |= 0x00000001;
              }
              transactions_.add(
                  input.readMessage(iroha.protocol.TransactionOuterClass.Transaction.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          transactions_ = java.util.Collections.unmodifiableList(transactions_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return iroha.protocol.Endpoint.internal_static_iroha_protocol_TxList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return iroha.protocol.Endpoint.internal_static_iroha_protocol_TxList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              iroha.protocol.Endpoint.TxList.class, iroha.protocol.Endpoint.TxList.Builder.class);
    }

    public static final int TRANSACTIONS_FIELD_NUMBER = 1;
    private java.util.List<iroha.protocol.TransactionOuterClass.Transaction> transactions_;
    /**
     * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
     */
    public java.util.List<iroha.protocol.TransactionOuterClass.Transaction> getTransactionsList() {
      return transactions_;
    }
    /**
     * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
     */
    public java.util.List<? extends iroha.protocol.TransactionOuterClass.TransactionOrBuilder> 
        getTransactionsOrBuilderList() {
      return transactions_;
    }
    /**
     * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
     */
    public int getTransactionsCount() {
      return transactions_.size();
    }
    /**
     * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
     */
    public iroha.protocol.TransactionOuterClass.Transaction getTransactions(int index) {
      return transactions_.get(index);
    }
    /**
     * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
     */
    public iroha.protocol.TransactionOuterClass.TransactionOrBuilder getTransactionsOrBuilder(
        int index) {
      return transactions_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < transactions_.size(); i++) {
        output.writeMessage(1, transactions_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < transactions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, transactions_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof iroha.protocol.Endpoint.TxList)) {
        return super.equals(obj);
      }
      iroha.protocol.Endpoint.TxList other = (iroha.protocol.Endpoint.TxList) obj;

      boolean result = true;
      result = result && getTransactionsList()
          .equals(other.getTransactionsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTransactionsCount() > 0) {
        hash = (37 * hash) + TRANSACTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getTransactionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static iroha.protocol.Endpoint.TxList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static iroha.protocol.Endpoint.TxList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static iroha.protocol.Endpoint.TxList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static iroha.protocol.Endpoint.TxList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static iroha.protocol.Endpoint.TxList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static iroha.protocol.Endpoint.TxList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static iroha.protocol.Endpoint.TxList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static iroha.protocol.Endpoint.TxList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static iroha.protocol.Endpoint.TxList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static iroha.protocol.Endpoint.TxList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static iroha.protocol.Endpoint.TxList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static iroha.protocol.Endpoint.TxList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(iroha.protocol.Endpoint.TxList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code iroha.protocol.TxList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:iroha.protocol.TxList)
        iroha.protocol.Endpoint.TxListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return iroha.protocol.Endpoint.internal_static_iroha_protocol_TxList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return iroha.protocol.Endpoint.internal_static_iroha_protocol_TxList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                iroha.protocol.Endpoint.TxList.class, iroha.protocol.Endpoint.TxList.Builder.class);
      }

      // Construct using iroha.protocol.Endpoint.TxList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTransactionsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (transactionsBuilder_ == null) {
          transactions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          transactionsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return iroha.protocol.Endpoint.internal_static_iroha_protocol_TxList_descriptor;
      }

      public iroha.protocol.Endpoint.TxList getDefaultInstanceForType() {
        return iroha.protocol.Endpoint.TxList.getDefaultInstance();
      }

      public iroha.protocol.Endpoint.TxList build() {
        iroha.protocol.Endpoint.TxList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public iroha.protocol.Endpoint.TxList buildPartial() {
        iroha.protocol.Endpoint.TxList result = new iroha.protocol.Endpoint.TxList(this);
        int from_bitField0_ = bitField0_;
        if (transactionsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            transactions_ = java.util.Collections.unmodifiableList(transactions_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.transactions_ = transactions_;
        } else {
          result.transactions_ = transactionsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof iroha.protocol.Endpoint.TxList) {
          return mergeFrom((iroha.protocol.Endpoint.TxList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(iroha.protocol.Endpoint.TxList other) {
        if (other == iroha.protocol.Endpoint.TxList.getDefaultInstance()) return this;
        if (transactionsBuilder_ == null) {
          if (!other.transactions_.isEmpty()) {
            if (transactions_.isEmpty()) {
              transactions_ = other.transactions_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTransactionsIsMutable();
              transactions_.addAll(other.transactions_);
            }
            onChanged();
          }
        } else {
          if (!other.transactions_.isEmpty()) {
            if (transactionsBuilder_.isEmpty()) {
              transactionsBuilder_.dispose();
              transactionsBuilder_ = null;
              transactions_ = other.transactions_;
              bitField0_ = (bitField0_ & ~0x00000001);
              transactionsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTransactionsFieldBuilder() : null;
            } else {
              transactionsBuilder_.addAllMessages(other.transactions_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        iroha.protocol.Endpoint.TxList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (iroha.protocol.Endpoint.TxList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<iroha.protocol.TransactionOuterClass.Transaction> transactions_ =
        java.util.Collections.emptyList();
      private void ensureTransactionsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          transactions_ = new java.util.ArrayList<iroha.protocol.TransactionOuterClass.Transaction>(transactions_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          iroha.protocol.TransactionOuterClass.Transaction, iroha.protocol.TransactionOuterClass.Transaction.Builder, iroha.protocol.TransactionOuterClass.TransactionOrBuilder> transactionsBuilder_;

      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public java.util.List<iroha.protocol.TransactionOuterClass.Transaction> getTransactionsList() {
        if (transactionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(transactions_);
        } else {
          return transactionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public int getTransactionsCount() {
        if (transactionsBuilder_ == null) {
          return transactions_.size();
        } else {
          return transactionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public iroha.protocol.TransactionOuterClass.Transaction getTransactions(int index) {
        if (transactionsBuilder_ == null) {
          return transactions_.get(index);
        } else {
          return transactionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public Builder setTransactions(
          int index, iroha.protocol.TransactionOuterClass.Transaction value) {
        if (transactionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTransactionsIsMutable();
          transactions_.set(index, value);
          onChanged();
        } else {
          transactionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public Builder setTransactions(
          int index, iroha.protocol.TransactionOuterClass.Transaction.Builder builderForValue) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          transactions_.set(index, builderForValue.build());
          onChanged();
        } else {
          transactionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public Builder addTransactions(iroha.protocol.TransactionOuterClass.Transaction value) {
        if (transactionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTransactionsIsMutable();
          transactions_.add(value);
          onChanged();
        } else {
          transactionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public Builder addTransactions(
          int index, iroha.protocol.TransactionOuterClass.Transaction value) {
        if (transactionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTransactionsIsMutable();
          transactions_.add(index, value);
          onChanged();
        } else {
          transactionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public Builder addTransactions(
          iroha.protocol.TransactionOuterClass.Transaction.Builder builderForValue) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          transactions_.add(builderForValue.build());
          onChanged();
        } else {
          transactionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public Builder addTransactions(
          int index, iroha.protocol.TransactionOuterClass.Transaction.Builder builderForValue) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          transactions_.add(index, builderForValue.build());
          onChanged();
        } else {
          transactionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public Builder addAllTransactions(
          java.lang.Iterable<? extends iroha.protocol.TransactionOuterClass.Transaction> values) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, transactions_);
          onChanged();
        } else {
          transactionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public Builder clearTransactions() {
        if (transactionsBuilder_ == null) {
          transactions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          transactionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public Builder removeTransactions(int index) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          transactions_.remove(index);
          onChanged();
        } else {
          transactionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public iroha.protocol.TransactionOuterClass.Transaction.Builder getTransactionsBuilder(
          int index) {
        return getTransactionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public iroha.protocol.TransactionOuterClass.TransactionOrBuilder getTransactionsOrBuilder(
          int index) {
        if (transactionsBuilder_ == null) {
          return transactions_.get(index);  } else {
          return transactionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public java.util.List<? extends iroha.protocol.TransactionOuterClass.TransactionOrBuilder> 
           getTransactionsOrBuilderList() {
        if (transactionsBuilder_ != null) {
          return transactionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(transactions_);
        }
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public iroha.protocol.TransactionOuterClass.Transaction.Builder addTransactionsBuilder() {
        return getTransactionsFieldBuilder().addBuilder(
            iroha.protocol.TransactionOuterClass.Transaction.getDefaultInstance());
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public iroha.protocol.TransactionOuterClass.Transaction.Builder addTransactionsBuilder(
          int index) {
        return getTransactionsFieldBuilder().addBuilder(
            index, iroha.protocol.TransactionOuterClass.Transaction.getDefaultInstance());
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public java.util.List<iroha.protocol.TransactionOuterClass.Transaction.Builder> 
           getTransactionsBuilderList() {
        return getTransactionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          iroha.protocol.TransactionOuterClass.Transaction, iroha.protocol.TransactionOuterClass.Transaction.Builder, iroha.protocol.TransactionOuterClass.TransactionOrBuilder> 
          getTransactionsFieldBuilder() {
        if (transactionsBuilder_ == null) {
          transactionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              iroha.protocol.TransactionOuterClass.Transaction, iroha.protocol.TransactionOuterClass.Transaction.Builder, iroha.protocol.TransactionOuterClass.TransactionOrBuilder>(
                  transactions_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          transactions_ = null;
        }
        return transactionsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:iroha.protocol.TxList)
    }

    // @@protoc_insertion_point(class_scope:iroha.protocol.TxList)
    private static final iroha.protocol.Endpoint.TxList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new iroha.protocol.Endpoint.TxList();
    }

    public static iroha.protocol.Endpoint.TxList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TxList>
        PARSER = new com.google.protobuf.AbstractParser<TxList>() {
      public TxList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TxList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TxList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TxList> getParserForType() {
      return PARSER;
    }

    public iroha.protocol.Endpoint.TxList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iroha_protocol_ToriiResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iroha_protocol_ToriiResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iroha_protocol_TxStatusRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iroha_protocol_TxStatusRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iroha_protocol_TxList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iroha_protocol_TxList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016endpoint.proto\022\016iroha.protocol\032\021transa" +
      "ction.proto\032\rqueries.proto\032\023qry_response" +
      "s.proto\032\033google/protobuf/empty.proto\"\224\001\n" +
      "\rToriiResponse\022+\n\ttx_status\030\001 \001(\0162\030.iroh" +
      "a.protocol.TxStatus\022\017\n\007tx_hash\030\002 \001(\t\022\027\n\017" +
      "err_or_cmd_name\030\003 \001(\t\022\030\n\020failed_cmd_inde" +
      "x\030\004 \001(\004\022\022\n\nerror_code\030\005 \001(\r\"\"\n\017TxStatusR" +
      "equest\022\017\n\007tx_hash\030\001 \001(\t\";\n\006TxList\0221\n\014tra" +
      "nsactions\030\001 \003(\0132\033.iroha.protocol.Transac" +
      "tion*\200\002\n\010TxStatus\022\037\n\033STATELESS_VALIDATIO" +
      "N_FAILED\020\000\022 \n\034STATELESS_VALIDATION_SUCCE" +
      "SS\020\001\022\036\n\032STATEFUL_VALIDATION_FAILED\020\002\022\037\n\033" +
      "STATEFUL_VALIDATION_SUCCESS\020\003\022\014\n\010REJECTE" +
      "D\020\004\022\r\n\tCOMMITTED\020\005\022\017\n\013MST_EXPIRED\020\006\022\020\n\014N" +
      "OT_RECEIVED\020\007\022\017\n\013MST_PENDING\020\010\022\037\n\033ENOUGH" +
      "_SIGNATURES_COLLECTED\020\t2\252\002\n\021CommandServi" +
      "ce_v1\022<\n\005Torii\022\033.iroha.protocol.Transact" +
      "ion\032\026.google.protobuf.Empty\022;\n\tListTorii" +
      "\022\026.iroha.protocol.TxList\032\026.google.protob" +
      "uf.Empty\022H\n\006Status\022\037.iroha.protocol.TxSt" +
      "atusRequest\032\035.iroha.protocol.ToriiRespon" +
      "se\022P\n\014StatusStream\022\037.iroha.protocol.TxSt" +
      "atusRequest\032\035.iroha.protocol.ToriiRespon" +
      "se0\0012\242\001\n\017QueryService_v1\022<\n\004Find\022\025.iroha" +
      ".protocol.Query\032\035.iroha.protocol.QueryRe" +
      "sponse\022Q\n\014FetchCommits\022\033.iroha.protocol." +
      "BlocksQuery\032\".iroha.protocol.BlockQueryR" +
      "esponse0\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          iroha.protocol.TransactionOuterClass.getDescriptor(),
          iroha.protocol.Queries.getDescriptor(),
          iroha.protocol.QryResponses.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_iroha_protocol_ToriiResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_iroha_protocol_ToriiResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iroha_protocol_ToriiResponse_descriptor,
        new java.lang.String[] { "TxStatus", "TxHash", "ErrOrCmdName", "FailedCmdIndex", "ErrorCode", });
    internal_static_iroha_protocol_TxStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_iroha_protocol_TxStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iroha_protocol_TxStatusRequest_descriptor,
        new java.lang.String[] { "TxHash", });
    internal_static_iroha_protocol_TxList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_iroha_protocol_TxList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iroha_protocol_TxList_descriptor,
        new java.lang.String[] { "Transactions", });
    iroha.protocol.TransactionOuterClass.getDescriptor();
    iroha.protocol.Queries.getDescriptor();
    iroha.protocol.QryResponses.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
