// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: primitive.proto

package iroha.protocol;

public final class Primitive {
  private Primitive() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   **
   * Represents any possible value for permission field,
   * then the account is capable of performing such action.
   * Command and Query related permissions are included in the role,
   * which an Account can have.
   * Grantable permission is set as a relation between two accounts:
   * Account A is granting Permission to Account B,
   * so that Account B can perform actions over Account A.
   * </pre>
   *
   * Protobuf enum {@code iroha.protocol.RolePermission}
   */
  public enum RolePermission
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Command Permissions
     * </pre>
     *
     * <code>can_append_role = 0;</code>
     */
    can_append_role(0),
    /**
     * <code>can_create_role = 1;</code>
     */
    can_create_role(1),
    /**
     * <code>can_detach_role = 2;</code>
     */
    can_detach_role(2),
    /**
     * <code>can_add_asset_qty = 3;</code>
     */
    can_add_asset_qty(3),
    /**
     * <code>can_subtract_asset_qty = 4;</code>
     */
    can_subtract_asset_qty(4),
    /**
     * <code>can_add_peer = 5;</code>
     */
    can_add_peer(5),
    /**
     * <code>can_add_signatory = 6;</code>
     */
    can_add_signatory(6),
    /**
     * <code>can_remove_signatory = 7;</code>
     */
    can_remove_signatory(7),
    /**
     * <code>can_set_quorum = 8;</code>
     */
    can_set_quorum(8),
    /**
     * <code>can_create_account = 9;</code>
     */
    can_create_account(9),
    /**
     * <code>can_set_detail = 10;</code>
     */
    can_set_detail(10),
    /**
     * <code>can_create_asset = 11;</code>
     */
    can_create_asset(11),
    /**
     * <code>can_transfer = 12;</code>
     */
    can_transfer(12),
    /**
     * <code>can_receive = 13;</code>
     */
    can_receive(13),
    /**
     * <code>can_create_domain = 14;</code>
     */
    can_create_domain(14),
    /**
     * <code>can_add_domain_asset_qty = 43;</code>
     */
    can_add_domain_asset_qty(43),
    /**
     * <code>can_subtract_domain_asset_qty = 44;</code>
     */
    can_subtract_domain_asset_qty(44),
    /**
     * <pre>
     * Query permissions
     * </pre>
     *
     * <code>can_read_assets = 15;</code>
     */
    can_read_assets(15),
    /**
     * <code>can_get_roles = 16;</code>
     */
    can_get_roles(16),
    /**
     * <code>can_get_my_account = 17;</code>
     */
    can_get_my_account(17),
    /**
     * <code>can_get_all_accounts = 18;</code>
     */
    can_get_all_accounts(18),
    /**
     * <code>can_get_domain_accounts = 19;</code>
     */
    can_get_domain_accounts(19),
    /**
     * <code>can_get_my_signatories = 20;</code>
     */
    can_get_my_signatories(20),
    /**
     * <code>can_get_all_signatories = 21;</code>
     */
    can_get_all_signatories(21),
    /**
     * <code>can_get_domain_signatories = 22;</code>
     */
    can_get_domain_signatories(22),
    /**
     * <code>can_get_my_acc_ast = 23;</code>
     */
    can_get_my_acc_ast(23),
    /**
     * <code>can_get_all_acc_ast = 24;</code>
     */
    can_get_all_acc_ast(24),
    /**
     * <code>can_get_domain_acc_ast = 25;</code>
     */
    can_get_domain_acc_ast(25),
    /**
     * <code>can_get_my_acc_detail = 26;</code>
     */
    can_get_my_acc_detail(26),
    /**
     * <code>can_get_all_acc_detail = 27;</code>
     */
    can_get_all_acc_detail(27),
    /**
     * <code>can_get_domain_acc_detail = 28;</code>
     */
    can_get_domain_acc_detail(28),
    /**
     * <code>can_get_my_acc_txs = 29;</code>
     */
    can_get_my_acc_txs(29),
    /**
     * <code>can_get_all_acc_txs = 30;</code>
     */
    can_get_all_acc_txs(30),
    /**
     * <code>can_get_domain_acc_txs = 31;</code>
     */
    can_get_domain_acc_txs(31),
    /**
     * <code>can_get_my_acc_ast_txs = 32;</code>
     */
    can_get_my_acc_ast_txs(32),
    /**
     * <code>can_get_all_acc_ast_txs = 33;</code>
     */
    can_get_all_acc_ast_txs(33),
    /**
     * <code>can_get_domain_acc_ast_txs = 34;</code>
     */
    can_get_domain_acc_ast_txs(34),
    /**
     * <code>can_get_my_txs = 35;</code>
     */
    can_get_my_txs(35),
    /**
     * <code>can_get_all_txs = 36;</code>
     */
    can_get_all_txs(36),
    /**
     * <code>can_get_blocks = 42;</code>
     */
    can_get_blocks(42),
    /**
     * <pre>
     * Grant permissions
     * </pre>
     *
     * <code>can_grant_can_set_my_quorum = 37;</code>
     */
    can_grant_can_set_my_quorum(37),
    /**
     * <code>can_grant_can_add_my_signatory = 38;</code>
     */
    can_grant_can_add_my_signatory(38),
    /**
     * <code>can_grant_can_remove_my_signatory = 39;</code>
     */
    can_grant_can_remove_my_signatory(39),
    /**
     * <code>can_grant_can_transfer_my_assets = 40;</code>
     */
    can_grant_can_transfer_my_assets(40),
    /**
     * <code>can_grant_can_set_my_account_detail = 41;</code>
     */
    can_grant_can_set_my_account_detail(41),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * Command Permissions
     * </pre>
     *
     * <code>can_append_role = 0;</code>
     */
    public static final int can_append_role_VALUE = 0;
    /**
     * <code>can_create_role = 1;</code>
     */
    public static final int can_create_role_VALUE = 1;
    /**
     * <code>can_detach_role = 2;</code>
     */
    public static final int can_detach_role_VALUE = 2;
    /**
     * <code>can_add_asset_qty = 3;</code>
     */
    public static final int can_add_asset_qty_VALUE = 3;
    /**
     * <code>can_subtract_asset_qty = 4;</code>
     */
    public static final int can_subtract_asset_qty_VALUE = 4;
    /**
     * <code>can_add_peer = 5;</code>
     */
    public static final int can_add_peer_VALUE = 5;
    /**
     * <code>can_add_signatory = 6;</code>
     */
    public static final int can_add_signatory_VALUE = 6;
    /**
     * <code>can_remove_signatory = 7;</code>
     */
    public static final int can_remove_signatory_VALUE = 7;
    /**
     * <code>can_set_quorum = 8;</code>
     */
    public static final int can_set_quorum_VALUE = 8;
    /**
     * <code>can_create_account = 9;</code>
     */
    public static final int can_create_account_VALUE = 9;
    /**
     * <code>can_set_detail = 10;</code>
     */
    public static final int can_set_detail_VALUE = 10;
    /**
     * <code>can_create_asset = 11;</code>
     */
    public static final int can_create_asset_VALUE = 11;
    /**
     * <code>can_transfer = 12;</code>
     */
    public static final int can_transfer_VALUE = 12;
    /**
     * <code>can_receive = 13;</code>
     */
    public static final int can_receive_VALUE = 13;
    /**
     * <code>can_create_domain = 14;</code>
     */
    public static final int can_create_domain_VALUE = 14;
    /**
     * <code>can_add_domain_asset_qty = 43;</code>
     */
    public static final int can_add_domain_asset_qty_VALUE = 43;
    /**
     * <code>can_subtract_domain_asset_qty = 44;</code>
     */
    public static final int can_subtract_domain_asset_qty_VALUE = 44;
    /**
     * <pre>
     * Query permissions
     * </pre>
     *
     * <code>can_read_assets = 15;</code>
     */
    public static final int can_read_assets_VALUE = 15;
    /**
     * <code>can_get_roles = 16;</code>
     */
    public static final int can_get_roles_VALUE = 16;
    /**
     * <code>can_get_my_account = 17;</code>
     */
    public static final int can_get_my_account_VALUE = 17;
    /**
     * <code>can_get_all_accounts = 18;</code>
     */
    public static final int can_get_all_accounts_VALUE = 18;
    /**
     * <code>can_get_domain_accounts = 19;</code>
     */
    public static final int can_get_domain_accounts_VALUE = 19;
    /**
     * <code>can_get_my_signatories = 20;</code>
     */
    public static final int can_get_my_signatories_VALUE = 20;
    /**
     * <code>can_get_all_signatories = 21;</code>
     */
    public static final int can_get_all_signatories_VALUE = 21;
    /**
     * <code>can_get_domain_signatories = 22;</code>
     */
    public static final int can_get_domain_signatories_VALUE = 22;
    /**
     * <code>can_get_my_acc_ast = 23;</code>
     */
    public static final int can_get_my_acc_ast_VALUE = 23;
    /**
     * <code>can_get_all_acc_ast = 24;</code>
     */
    public static final int can_get_all_acc_ast_VALUE = 24;
    /**
     * <code>can_get_domain_acc_ast = 25;</code>
     */
    public static final int can_get_domain_acc_ast_VALUE = 25;
    /**
     * <code>can_get_my_acc_detail = 26;</code>
     */
    public static final int can_get_my_acc_detail_VALUE = 26;
    /**
     * <code>can_get_all_acc_detail = 27;</code>
     */
    public static final int can_get_all_acc_detail_VALUE = 27;
    /**
     * <code>can_get_domain_acc_detail = 28;</code>
     */
    public static final int can_get_domain_acc_detail_VALUE = 28;
    /**
     * <code>can_get_my_acc_txs = 29;</code>
     */
    public static final int can_get_my_acc_txs_VALUE = 29;
    /**
     * <code>can_get_all_acc_txs = 30;</code>
     */
    public static final int can_get_all_acc_txs_VALUE = 30;
    /**
     * <code>can_get_domain_acc_txs = 31;</code>
     */
    public static final int can_get_domain_acc_txs_VALUE = 31;
    /**
     * <code>can_get_my_acc_ast_txs = 32;</code>
     */
    public static final int can_get_my_acc_ast_txs_VALUE = 32;
    /**
     * <code>can_get_all_acc_ast_txs = 33;</code>
     */
    public static final int can_get_all_acc_ast_txs_VALUE = 33;
    /**
     * <code>can_get_domain_acc_ast_txs = 34;</code>
     */
    public static final int can_get_domain_acc_ast_txs_VALUE = 34;
    /**
     * <code>can_get_my_txs = 35;</code>
     */
    public static final int can_get_my_txs_VALUE = 35;
    /**
     * <code>can_get_all_txs = 36;</code>
     */
    public static final int can_get_all_txs_VALUE = 36;
    /**
     * <code>can_get_blocks = 42;</code>
     */
    public static final int can_get_blocks_VALUE = 42;
    /**
     * <pre>
     * Grant permissions
     * </pre>
     *
     * <code>can_grant_can_set_my_quorum = 37;</code>
     */
    public static final int can_grant_can_set_my_quorum_VALUE = 37;
    /**
     * <code>can_grant_can_add_my_signatory = 38;</code>
     */
    public static final int can_grant_can_add_my_signatory_VALUE = 38;
    /**
     * <code>can_grant_can_remove_my_signatory = 39;</code>
     */
    public static final int can_grant_can_remove_my_signatory_VALUE = 39;
    /**
     * <code>can_grant_can_transfer_my_assets = 40;</code>
     */
    public static final int can_grant_can_transfer_my_assets_VALUE = 40;
    /**
     * <code>can_grant_can_set_my_account_detail = 41;</code>
     */
    public static final int can_grant_can_set_my_account_detail_VALUE = 41;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RolePermission valueOf(int value) {
      return forNumber(value);
    }

    public static RolePermission forNumber(int value) {
      switch (value) {
        case 0: return can_append_role;
        case 1: return can_create_role;
        case 2: return can_detach_role;
        case 3: return can_add_asset_qty;
        case 4: return can_subtract_asset_qty;
        case 5: return can_add_peer;
        case 6: return can_add_signatory;
        case 7: return can_remove_signatory;
        case 8: return can_set_quorum;
        case 9: return can_create_account;
        case 10: return can_set_detail;
        case 11: return can_create_asset;
        case 12: return can_transfer;
        case 13: return can_receive;
        case 14: return can_create_domain;
        case 43: return can_add_domain_asset_qty;
        case 44: return can_subtract_domain_asset_qty;
        case 15: return can_read_assets;
        case 16: return can_get_roles;
        case 17: return can_get_my_account;
        case 18: return can_get_all_accounts;
        case 19: return can_get_domain_accounts;
        case 20: return can_get_my_signatories;
        case 21: return can_get_all_signatories;
        case 22: return can_get_domain_signatories;
        case 23: return can_get_my_acc_ast;
        case 24: return can_get_all_acc_ast;
        case 25: return can_get_domain_acc_ast;
        case 26: return can_get_my_acc_detail;
        case 27: return can_get_all_acc_detail;
        case 28: return can_get_domain_acc_detail;
        case 29: return can_get_my_acc_txs;
        case 30: return can_get_all_acc_txs;
        case 31: return can_get_domain_acc_txs;
        case 32: return can_get_my_acc_ast_txs;
        case 33: return can_get_all_acc_ast_txs;
        case 34: return can_get_domain_acc_ast_txs;
        case 35: return can_get_my_txs;
        case 36: return can_get_all_txs;
        case 42: return can_get_blocks;
        case 37: return can_grant_can_set_my_quorum;
        case 38: return can_grant_can_add_my_signatory;
        case 39: return can_grant_can_remove_my_signatory;
        case 40: return can_grant_can_transfer_my_assets;
        case 41: return can_grant_can_set_my_account_detail;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RolePermission>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RolePermission> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RolePermission>() {
            public RolePermission findValueByNumber(int number) {
              return RolePermission.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return iroha.protocol.Primitive.getDescriptor().getEnumTypes().get(0);
    }

    private static final RolePermission[] VALUES = values();

    public static RolePermission valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RolePermission(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:iroha.protocol.RolePermission)
  }

  /**
   * Protobuf enum {@code iroha.protocol.GrantablePermission}
   */
  public enum GrantablePermission
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>can_add_my_signatory = 0;</code>
     */
    can_add_my_signatory(0),
    /**
     * <code>can_remove_my_signatory = 1;</code>
     */
    can_remove_my_signatory(1),
    /**
     * <code>can_set_my_quorum = 2;</code>
     */
    can_set_my_quorum(2),
    /**
     * <code>can_set_my_account_detail = 3;</code>
     */
    can_set_my_account_detail(3),
    /**
     * <pre>
     * not implemented now
     * </pre>
     *
     * <code>can_transfer_my_assets = 4;</code>
     */
    can_transfer_my_assets(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>can_add_my_signatory = 0;</code>
     */
    public static final int can_add_my_signatory_VALUE = 0;
    /**
     * <code>can_remove_my_signatory = 1;</code>
     */
    public static final int can_remove_my_signatory_VALUE = 1;
    /**
     * <code>can_set_my_quorum = 2;</code>
     */
    public static final int can_set_my_quorum_VALUE = 2;
    /**
     * <code>can_set_my_account_detail = 3;</code>
     */
    public static final int can_set_my_account_detail_VALUE = 3;
    /**
     * <pre>
     * not implemented now
     * </pre>
     *
     * <code>can_transfer_my_assets = 4;</code>
     */
    public static final int can_transfer_my_assets_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static GrantablePermission valueOf(int value) {
      return forNumber(value);
    }

    public static GrantablePermission forNumber(int value) {
      switch (value) {
        case 0: return can_add_my_signatory;
        case 1: return can_remove_my_signatory;
        case 2: return can_set_my_quorum;
        case 3: return can_set_my_account_detail;
        case 4: return can_transfer_my_assets;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GrantablePermission>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        GrantablePermission> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GrantablePermission>() {
            public GrantablePermission findValueByNumber(int number) {
              return GrantablePermission.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return iroha.protocol.Primitive.getDescriptor().getEnumTypes().get(1);
    }

    private static final GrantablePermission[] VALUES = values();

    public static GrantablePermission valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private GrantablePermission(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:iroha.protocol.GrantablePermission)
  }

  public interface SignatureOrBuilder extends
      // @@protoc_insertion_point(interface_extends:iroha.protocol.Signature)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string public_key = 1;</code>
     */
    java.lang.String getPublicKey();
    /**
     * <code>string public_key = 1;</code>
     */
    com.google.protobuf.ByteString
        getPublicKeyBytes();

    /**
     * <code>string signature = 2;</code>
     */
    java.lang.String getSignature();
    /**
     * <code>string signature = 2;</code>
     */
    com.google.protobuf.ByteString
        getSignatureBytes();
  }
  /**
   * Protobuf type {@code iroha.protocol.Signature}
   */
  public  static final class Signature extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:iroha.protocol.Signature)
      SignatureOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Signature.newBuilder() to construct.
    private Signature(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Signature() {
      publicKey_ = "";
      signature_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Signature(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              publicKey_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              signature_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return iroha.protocol.Primitive.internal_static_iroha_protocol_Signature_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return iroha.protocol.Primitive.internal_static_iroha_protocol_Signature_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              iroha.protocol.Primitive.Signature.class, iroha.protocol.Primitive.Signature.Builder.class);
    }

    public static final int PUBLIC_KEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object publicKey_;
    /**
     * <code>string public_key = 1;</code>
     */
    public java.lang.String getPublicKey() {
      java.lang.Object ref = publicKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        publicKey_ = s;
        return s;
      }
    }
    /**
     * <code>string public_key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPublicKeyBytes() {
      java.lang.Object ref = publicKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        publicKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIGNATURE_FIELD_NUMBER = 2;
    private volatile java.lang.Object signature_;
    /**
     * <code>string signature = 2;</code>
     */
    public java.lang.String getSignature() {
      java.lang.Object ref = signature_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        signature_ = s;
        return s;
      }
    }
    /**
     * <code>string signature = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSignatureBytes() {
      java.lang.Object ref = signature_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPublicKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, publicKey_);
      }
      if (!getSignatureBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, signature_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPublicKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, publicKey_);
      }
      if (!getSignatureBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, signature_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof iroha.protocol.Primitive.Signature)) {
        return super.equals(obj);
      }
      iroha.protocol.Primitive.Signature other = (iroha.protocol.Primitive.Signature) obj;

      boolean result = true;
      result = result && getPublicKey()
          .equals(other.getPublicKey());
      result = result && getSignature()
          .equals(other.getSignature());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PUBLIC_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getPublicKey().hashCode();
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static iroha.protocol.Primitive.Signature parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static iroha.protocol.Primitive.Signature parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static iroha.protocol.Primitive.Signature parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static iroha.protocol.Primitive.Signature parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static iroha.protocol.Primitive.Signature parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static iroha.protocol.Primitive.Signature parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static iroha.protocol.Primitive.Signature parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static iroha.protocol.Primitive.Signature parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static iroha.protocol.Primitive.Signature parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static iroha.protocol.Primitive.Signature parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static iroha.protocol.Primitive.Signature parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static iroha.protocol.Primitive.Signature parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(iroha.protocol.Primitive.Signature prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code iroha.protocol.Signature}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:iroha.protocol.Signature)
        iroha.protocol.Primitive.SignatureOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return iroha.protocol.Primitive.internal_static_iroha_protocol_Signature_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return iroha.protocol.Primitive.internal_static_iroha_protocol_Signature_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                iroha.protocol.Primitive.Signature.class, iroha.protocol.Primitive.Signature.Builder.class);
      }

      // Construct using iroha.protocol.Primitive.Signature.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        publicKey_ = "";

        signature_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return iroha.protocol.Primitive.internal_static_iroha_protocol_Signature_descriptor;
      }

      public iroha.protocol.Primitive.Signature getDefaultInstanceForType() {
        return iroha.protocol.Primitive.Signature.getDefaultInstance();
      }

      public iroha.protocol.Primitive.Signature build() {
        iroha.protocol.Primitive.Signature result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public iroha.protocol.Primitive.Signature buildPartial() {
        iroha.protocol.Primitive.Signature result = new iroha.protocol.Primitive.Signature(this);
        result.publicKey_ = publicKey_;
        result.signature_ = signature_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof iroha.protocol.Primitive.Signature) {
          return mergeFrom((iroha.protocol.Primitive.Signature)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(iroha.protocol.Primitive.Signature other) {
        if (other == iroha.protocol.Primitive.Signature.getDefaultInstance()) return this;
        if (!other.getPublicKey().isEmpty()) {
          publicKey_ = other.publicKey_;
          onChanged();
        }
        if (!other.getSignature().isEmpty()) {
          signature_ = other.signature_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        iroha.protocol.Primitive.Signature parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (iroha.protocol.Primitive.Signature) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object publicKey_ = "";
      /**
       * <code>string public_key = 1;</code>
       */
      public java.lang.String getPublicKey() {
        java.lang.Object ref = publicKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          publicKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string public_key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPublicKeyBytes() {
        java.lang.Object ref = publicKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          publicKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string public_key = 1;</code>
       */
      public Builder setPublicKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        publicKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string public_key = 1;</code>
       */
      public Builder clearPublicKey() {
        
        publicKey_ = getDefaultInstance().getPublicKey();
        onChanged();
        return this;
      }
      /**
       * <code>string public_key = 1;</code>
       */
      public Builder setPublicKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        publicKey_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object signature_ = "";
      /**
       * <code>string signature = 2;</code>
       */
      public java.lang.String getSignature() {
        java.lang.Object ref = signature_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          signature_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string signature = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSignatureBytes() {
        java.lang.Object ref = signature_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          signature_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string signature = 2;</code>
       */
      public Builder setSignature(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string signature = 2;</code>
       */
      public Builder clearSignature() {
        
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      /**
       * <code>string signature = 2;</code>
       */
      public Builder setSignatureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        signature_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:iroha.protocol.Signature)
    }

    // @@protoc_insertion_point(class_scope:iroha.protocol.Signature)
    private static final iroha.protocol.Primitive.Signature DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new iroha.protocol.Primitive.Signature();
    }

    public static iroha.protocol.Primitive.Signature getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Signature>
        PARSER = new com.google.protobuf.AbstractParser<Signature>() {
      public Signature parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Signature(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Signature> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Signature> getParserForType() {
      return PARSER;
    }

    public iroha.protocol.Primitive.Signature getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PeerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:iroha.protocol.Peer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string address = 1;</code>
     */
    java.lang.String getAddress();
    /**
     * <code>string address = 1;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <pre>
     * hex string
     * </pre>
     *
     * <code>string peer_key = 2;</code>
     */
    java.lang.String getPeerKey();
    /**
     * <pre>
     * hex string
     * </pre>
     *
     * <code>string peer_key = 2;</code>
     */
    com.google.protobuf.ByteString
        getPeerKeyBytes();
  }
  /**
   * Protobuf type {@code iroha.protocol.Peer}
   */
  public  static final class Peer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:iroha.protocol.Peer)
      PeerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Peer.newBuilder() to construct.
    private Peer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Peer() {
      address_ = "";
      peerKey_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Peer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              peerKey_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return iroha.protocol.Primitive.internal_static_iroha_protocol_Peer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return iroha.protocol.Primitive.internal_static_iroha_protocol_Peer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              iroha.protocol.Primitive.Peer.class, iroha.protocol.Primitive.Peer.Builder.class);
    }

    public static final int ADDRESS_FIELD_NUMBER = 1;
    private volatile java.lang.Object address_;
    /**
     * <code>string address = 1;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string address = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PEER_KEY_FIELD_NUMBER = 2;
    private volatile java.lang.Object peerKey_;
    /**
     * <pre>
     * hex string
     * </pre>
     *
     * <code>string peer_key = 2;</code>
     */
    public java.lang.String getPeerKey() {
      java.lang.Object ref = peerKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        peerKey_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * hex string
     * </pre>
     *
     * <code>string peer_key = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPeerKeyBytes() {
      java.lang.Object ref = peerKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        peerKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, address_);
      }
      if (!getPeerKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, peerKey_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, address_);
      }
      if (!getPeerKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, peerKey_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof iroha.protocol.Primitive.Peer)) {
        return super.equals(obj);
      }
      iroha.protocol.Primitive.Peer other = (iroha.protocol.Primitive.Peer) obj;

      boolean result = true;
      result = result && getAddress()
          .equals(other.getAddress());
      result = result && getPeerKey()
          .equals(other.getPeerKey());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + PEER_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getPeerKey().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static iroha.protocol.Primitive.Peer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static iroha.protocol.Primitive.Peer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static iroha.protocol.Primitive.Peer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static iroha.protocol.Primitive.Peer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static iroha.protocol.Primitive.Peer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static iroha.protocol.Primitive.Peer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static iroha.protocol.Primitive.Peer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static iroha.protocol.Primitive.Peer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static iroha.protocol.Primitive.Peer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static iroha.protocol.Primitive.Peer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static iroha.protocol.Primitive.Peer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static iroha.protocol.Primitive.Peer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(iroha.protocol.Primitive.Peer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code iroha.protocol.Peer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:iroha.protocol.Peer)
        iroha.protocol.Primitive.PeerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return iroha.protocol.Primitive.internal_static_iroha_protocol_Peer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return iroha.protocol.Primitive.internal_static_iroha_protocol_Peer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                iroha.protocol.Primitive.Peer.class, iroha.protocol.Primitive.Peer.Builder.class);
      }

      // Construct using iroha.protocol.Primitive.Peer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        address_ = "";

        peerKey_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return iroha.protocol.Primitive.internal_static_iroha_protocol_Peer_descriptor;
      }

      public iroha.protocol.Primitive.Peer getDefaultInstanceForType() {
        return iroha.protocol.Primitive.Peer.getDefaultInstance();
      }

      public iroha.protocol.Primitive.Peer build() {
        iroha.protocol.Primitive.Peer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public iroha.protocol.Primitive.Peer buildPartial() {
        iroha.protocol.Primitive.Peer result = new iroha.protocol.Primitive.Peer(this);
        result.address_ = address_;
        result.peerKey_ = peerKey_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof iroha.protocol.Primitive.Peer) {
          return mergeFrom((iroha.protocol.Primitive.Peer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(iroha.protocol.Primitive.Peer other) {
        if (other == iroha.protocol.Primitive.Peer.getDefaultInstance()) return this;
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (!other.getPeerKey().isEmpty()) {
          peerKey_ = other.peerKey_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        iroha.protocol.Primitive.Peer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (iroha.protocol.Primitive.Peer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>string address = 1;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string address = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address = 1;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string address = 1;</code>
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string address = 1;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object peerKey_ = "";
      /**
       * <pre>
       * hex string
       * </pre>
       *
       * <code>string peer_key = 2;</code>
       */
      public java.lang.String getPeerKey() {
        java.lang.Object ref = peerKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          peerKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * hex string
       * </pre>
       *
       * <code>string peer_key = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPeerKeyBytes() {
        java.lang.Object ref = peerKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          peerKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * hex string
       * </pre>
       *
       * <code>string peer_key = 2;</code>
       */
      public Builder setPeerKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        peerKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * hex string
       * </pre>
       *
       * <code>string peer_key = 2;</code>
       */
      public Builder clearPeerKey() {
        
        peerKey_ = getDefaultInstance().getPeerKey();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * hex string
       * </pre>
       *
       * <code>string peer_key = 2;</code>
       */
      public Builder setPeerKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        peerKey_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:iroha.protocol.Peer)
    }

    // @@protoc_insertion_point(class_scope:iroha.protocol.Peer)
    private static final iroha.protocol.Primitive.Peer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new iroha.protocol.Primitive.Peer();
    }

    public static iroha.protocol.Primitive.Peer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Peer>
        PARSER = new com.google.protobuf.AbstractParser<Peer>() {
      public Peer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Peer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Peer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Peer> getParserForType() {
      return PARSER;
    }

    public iroha.protocol.Primitive.Peer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iroha_protocol_Signature_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iroha_protocol_Signature_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iroha_protocol_Peer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iroha_protocol_Peer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017primitive.proto\022\016iroha.protocol\"2\n\tSig" +
      "nature\022\022\n\npublic_key\030\001 \001(\t\022\021\n\tsignature\030" +
      "\002 \001(\t\")\n\004Peer\022\017\n\007address\030\001 \001(\t\022\020\n\010peer_k" +
      "ey\030\002 \001(\t*\247\t\n\016RolePermission\022\023\n\017can_appen" +
      "d_role\020\000\022\023\n\017can_create_role\020\001\022\023\n\017can_det" +
      "ach_role\020\002\022\025\n\021can_add_asset_qty\020\003\022\032\n\026can" +
      "_subtract_asset_qty\020\004\022\020\n\014can_add_peer\020\005\022" +
      "\025\n\021can_add_signatory\020\006\022\030\n\024can_remove_sig" +
      "natory\020\007\022\022\n\016can_set_quorum\020\010\022\026\n\022can_crea" +
      "te_account\020\t\022\022\n\016can_set_detail\020\n\022\024\n\020can_" +
      "create_asset\020\013\022\020\n\014can_transfer\020\014\022\017\n\013can_" +
      "receive\020\r\022\025\n\021can_create_domain\020\016\022\034\n\030can_" +
      "add_domain_asset_qty\020+\022!\n\035can_subtract_d" +
      "omain_asset_qty\020,\022\023\n\017can_read_assets\020\017\022\021" +
      "\n\rcan_get_roles\020\020\022\026\n\022can_get_my_account\020" +
      "\021\022\030\n\024can_get_all_accounts\020\022\022\033\n\027can_get_d" +
      "omain_accounts\020\023\022\032\n\026can_get_my_signatori" +
      "es\020\024\022\033\n\027can_get_all_signatories\020\025\022\036\n\032can" +
      "_get_domain_signatories\020\026\022\026\n\022can_get_my_" +
      "acc_ast\020\027\022\027\n\023can_get_all_acc_ast\020\030\022\032\n\026ca" +
      "n_get_domain_acc_ast\020\031\022\031\n\025can_get_my_acc" +
      "_detail\020\032\022\032\n\026can_get_all_acc_detail\020\033\022\035\n" +
      "\031can_get_domain_acc_detail\020\034\022\026\n\022can_get_" +
      "my_acc_txs\020\035\022\027\n\023can_get_all_acc_txs\020\036\022\032\n" +
      "\026can_get_domain_acc_txs\020\037\022\032\n\026can_get_my_" +
      "acc_ast_txs\020 \022\033\n\027can_get_all_acc_ast_txs" +
      "\020!\022\036\n\032can_get_domain_acc_ast_txs\020\"\022\022\n\016ca" +
      "n_get_my_txs\020#\022\023\n\017can_get_all_txs\020$\022\022\n\016c" +
      "an_get_blocks\020*\022\037\n\033can_grant_can_set_my_" +
      "quorum\020%\022\"\n\036can_grant_can_add_my_signato" +
      "ry\020&\022%\n!can_grant_can_remove_my_signator" +
      "y\020\'\022$\n can_grant_can_transfer_my_assets\020" +
      "(\022\'\n#can_grant_can_set_my_account_detail" +
      "\020)*\236\001\n\023GrantablePermission\022\030\n\024can_add_my" +
      "_signatory\020\000\022\033\n\027can_remove_my_signatory\020" +
      "\001\022\025\n\021can_set_my_quorum\020\002\022\035\n\031can_set_my_a" +
      "ccount_detail\020\003\022\032\n\026can_transfer_my_asset" +
      "s\020\004b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_iroha_protocol_Signature_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_iroha_protocol_Signature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iroha_protocol_Signature_descriptor,
        new java.lang.String[] { "PublicKey", "Signature", });
    internal_static_iroha_protocol_Peer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_iroha_protocol_Peer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iroha_protocol_Peer_descriptor,
        new java.lang.String[] { "Address", "PeerKey", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
