// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mst.proto

package iroha.network.transport;

public final class Mst {
  private Mst() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MstStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:iroha.network.transport.MstState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
     */
    java.util.List<iroha.protocol.TransactionOuterClass.Transaction> 
        getTransactionsList();
    /**
     * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
     */
    iroha.protocol.TransactionOuterClass.Transaction getTransactions(int index);
    /**
     * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
     */
    int getTransactionsCount();
    /**
     * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
     */
    java.util.List<? extends iroha.protocol.TransactionOuterClass.TransactionOrBuilder> 
        getTransactionsOrBuilderList();
    /**
     * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
     */
    iroha.protocol.TransactionOuterClass.TransactionOrBuilder getTransactionsOrBuilder(
        int index);

    /**
     * <code>bytes source_peer_key = 2;</code>
     */
    com.google.protobuf.ByteString getSourcePeerKey();
  }
  /**
   * Protobuf type {@code iroha.network.transport.MstState}
   */
  public  static final class MstState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:iroha.network.transport.MstState)
      MstStateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MstState.newBuilder() to construct.
    private MstState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MstState() {
      transactions_ = java.util.Collections.emptyList();
      sourcePeerKey_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MstState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                transactions_ = new java.util.ArrayList<iroha.protocol.TransactionOuterClass.Transaction>();
                mutable_bitField0_ |= 0x00000001;
              }
              transactions_.add(
                  input.readMessage(iroha.protocol.TransactionOuterClass.Transaction.parser(), extensionRegistry));
              break;
            }
            case 18: {

              sourcePeerKey_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          transactions_ = java.util.Collections.unmodifiableList(transactions_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return iroha.network.transport.Mst.internal_static_iroha_network_transport_MstState_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return iroha.network.transport.Mst.internal_static_iroha_network_transport_MstState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              iroha.network.transport.Mst.MstState.class, iroha.network.transport.Mst.MstState.Builder.class);
    }

    private int bitField0_;
    public static final int TRANSACTIONS_FIELD_NUMBER = 1;
    private java.util.List<iroha.protocol.TransactionOuterClass.Transaction> transactions_;
    /**
     * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
     */
    public java.util.List<iroha.protocol.TransactionOuterClass.Transaction> getTransactionsList() {
      return transactions_;
    }
    /**
     * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
     */
    public java.util.List<? extends iroha.protocol.TransactionOuterClass.TransactionOrBuilder> 
        getTransactionsOrBuilderList() {
      return transactions_;
    }
    /**
     * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
     */
    public int getTransactionsCount() {
      return transactions_.size();
    }
    /**
     * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
     */
    public iroha.protocol.TransactionOuterClass.Transaction getTransactions(int index) {
      return transactions_.get(index);
    }
    /**
     * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
     */
    public iroha.protocol.TransactionOuterClass.TransactionOrBuilder getTransactionsOrBuilder(
        int index) {
      return transactions_.get(index);
    }

    public static final int SOURCE_PEER_KEY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString sourcePeerKey_;
    /**
     * <code>bytes source_peer_key = 2;</code>
     */
    public com.google.protobuf.ByteString getSourcePeerKey() {
      return sourcePeerKey_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < transactions_.size(); i++) {
        output.writeMessage(1, transactions_.get(i));
      }
      if (!sourcePeerKey_.isEmpty()) {
        output.writeBytes(2, sourcePeerKey_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < transactions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, transactions_.get(i));
      }
      if (!sourcePeerKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, sourcePeerKey_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof iroha.network.transport.Mst.MstState)) {
        return super.equals(obj);
      }
      iroha.network.transport.Mst.MstState other = (iroha.network.transport.Mst.MstState) obj;

      boolean result = true;
      result = result && getTransactionsList()
          .equals(other.getTransactionsList());
      result = result && getSourcePeerKey()
          .equals(other.getSourcePeerKey());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTransactionsCount() > 0) {
        hash = (37 * hash) + TRANSACTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getTransactionsList().hashCode();
      }
      hash = (37 * hash) + SOURCE_PEER_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getSourcePeerKey().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static iroha.network.transport.Mst.MstState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static iroha.network.transport.Mst.MstState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static iroha.network.transport.Mst.MstState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static iroha.network.transport.Mst.MstState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static iroha.network.transport.Mst.MstState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static iroha.network.transport.Mst.MstState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static iroha.network.transport.Mst.MstState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static iroha.network.transport.Mst.MstState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static iroha.network.transport.Mst.MstState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static iroha.network.transport.Mst.MstState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static iroha.network.transport.Mst.MstState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static iroha.network.transport.Mst.MstState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(iroha.network.transport.Mst.MstState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code iroha.network.transport.MstState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:iroha.network.transport.MstState)
        iroha.network.transport.Mst.MstStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return iroha.network.transport.Mst.internal_static_iroha_network_transport_MstState_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return iroha.network.transport.Mst.internal_static_iroha_network_transport_MstState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                iroha.network.transport.Mst.MstState.class, iroha.network.transport.Mst.MstState.Builder.class);
      }

      // Construct using iroha.network.transport.Mst.MstState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTransactionsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (transactionsBuilder_ == null) {
          transactions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          transactionsBuilder_.clear();
        }
        sourcePeerKey_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return iroha.network.transport.Mst.internal_static_iroha_network_transport_MstState_descriptor;
      }

      public iroha.network.transport.Mst.MstState getDefaultInstanceForType() {
        return iroha.network.transport.Mst.MstState.getDefaultInstance();
      }

      public iroha.network.transport.Mst.MstState build() {
        iroha.network.transport.Mst.MstState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public iroha.network.transport.Mst.MstState buildPartial() {
        iroha.network.transport.Mst.MstState result = new iroha.network.transport.Mst.MstState(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (transactionsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            transactions_ = java.util.Collections.unmodifiableList(transactions_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.transactions_ = transactions_;
        } else {
          result.transactions_ = transactionsBuilder_.build();
        }
        result.sourcePeerKey_ = sourcePeerKey_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof iroha.network.transport.Mst.MstState) {
          return mergeFrom((iroha.network.transport.Mst.MstState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(iroha.network.transport.Mst.MstState other) {
        if (other == iroha.network.transport.Mst.MstState.getDefaultInstance()) return this;
        if (transactionsBuilder_ == null) {
          if (!other.transactions_.isEmpty()) {
            if (transactions_.isEmpty()) {
              transactions_ = other.transactions_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTransactionsIsMutable();
              transactions_.addAll(other.transactions_);
            }
            onChanged();
          }
        } else {
          if (!other.transactions_.isEmpty()) {
            if (transactionsBuilder_.isEmpty()) {
              transactionsBuilder_.dispose();
              transactionsBuilder_ = null;
              transactions_ = other.transactions_;
              bitField0_ = (bitField0_ & ~0x00000001);
              transactionsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTransactionsFieldBuilder() : null;
            } else {
              transactionsBuilder_.addAllMessages(other.transactions_);
            }
          }
        }
        if (other.getSourcePeerKey() != com.google.protobuf.ByteString.EMPTY) {
          setSourcePeerKey(other.getSourcePeerKey());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        iroha.network.transport.Mst.MstState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (iroha.network.transport.Mst.MstState) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<iroha.protocol.TransactionOuterClass.Transaction> transactions_ =
        java.util.Collections.emptyList();
      private void ensureTransactionsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          transactions_ = new java.util.ArrayList<iroha.protocol.TransactionOuterClass.Transaction>(transactions_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          iroha.protocol.TransactionOuterClass.Transaction, iroha.protocol.TransactionOuterClass.Transaction.Builder, iroha.protocol.TransactionOuterClass.TransactionOrBuilder> transactionsBuilder_;

      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public java.util.List<iroha.protocol.TransactionOuterClass.Transaction> getTransactionsList() {
        if (transactionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(transactions_);
        } else {
          return transactionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public int getTransactionsCount() {
        if (transactionsBuilder_ == null) {
          return transactions_.size();
        } else {
          return transactionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public iroha.protocol.TransactionOuterClass.Transaction getTransactions(int index) {
        if (transactionsBuilder_ == null) {
          return transactions_.get(index);
        } else {
          return transactionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public Builder setTransactions(
          int index, iroha.protocol.TransactionOuterClass.Transaction value) {
        if (transactionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTransactionsIsMutable();
          transactions_.set(index, value);
          onChanged();
        } else {
          transactionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public Builder setTransactions(
          int index, iroha.protocol.TransactionOuterClass.Transaction.Builder builderForValue) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          transactions_.set(index, builderForValue.build());
          onChanged();
        } else {
          transactionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public Builder addTransactions(iroha.protocol.TransactionOuterClass.Transaction value) {
        if (transactionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTransactionsIsMutable();
          transactions_.add(value);
          onChanged();
        } else {
          transactionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public Builder addTransactions(
          int index, iroha.protocol.TransactionOuterClass.Transaction value) {
        if (transactionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTransactionsIsMutable();
          transactions_.add(index, value);
          onChanged();
        } else {
          transactionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public Builder addTransactions(
          iroha.protocol.TransactionOuterClass.Transaction.Builder builderForValue) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          transactions_.add(builderForValue.build());
          onChanged();
        } else {
          transactionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public Builder addTransactions(
          int index, iroha.protocol.TransactionOuterClass.Transaction.Builder builderForValue) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          transactions_.add(index, builderForValue.build());
          onChanged();
        } else {
          transactionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public Builder addAllTransactions(
          java.lang.Iterable<? extends iroha.protocol.TransactionOuterClass.Transaction> values) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, transactions_);
          onChanged();
        } else {
          transactionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public Builder clearTransactions() {
        if (transactionsBuilder_ == null) {
          transactions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          transactionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public Builder removeTransactions(int index) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          transactions_.remove(index);
          onChanged();
        } else {
          transactionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public iroha.protocol.TransactionOuterClass.Transaction.Builder getTransactionsBuilder(
          int index) {
        return getTransactionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public iroha.protocol.TransactionOuterClass.TransactionOrBuilder getTransactionsOrBuilder(
          int index) {
        if (transactionsBuilder_ == null) {
          return transactions_.get(index);  } else {
          return transactionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public java.util.List<? extends iroha.protocol.TransactionOuterClass.TransactionOrBuilder> 
           getTransactionsOrBuilderList() {
        if (transactionsBuilder_ != null) {
          return transactionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(transactions_);
        }
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public iroha.protocol.TransactionOuterClass.Transaction.Builder addTransactionsBuilder() {
        return getTransactionsFieldBuilder().addBuilder(
            iroha.protocol.TransactionOuterClass.Transaction.getDefaultInstance());
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public iroha.protocol.TransactionOuterClass.Transaction.Builder addTransactionsBuilder(
          int index) {
        return getTransactionsFieldBuilder().addBuilder(
            index, iroha.protocol.TransactionOuterClass.Transaction.getDefaultInstance());
      }
      /**
       * <code>repeated .iroha.protocol.Transaction transactions = 1;</code>
       */
      public java.util.List<iroha.protocol.TransactionOuterClass.Transaction.Builder> 
           getTransactionsBuilderList() {
        return getTransactionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          iroha.protocol.TransactionOuterClass.Transaction, iroha.protocol.TransactionOuterClass.Transaction.Builder, iroha.protocol.TransactionOuterClass.TransactionOrBuilder> 
          getTransactionsFieldBuilder() {
        if (transactionsBuilder_ == null) {
          transactionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              iroha.protocol.TransactionOuterClass.Transaction, iroha.protocol.TransactionOuterClass.Transaction.Builder, iroha.protocol.TransactionOuterClass.TransactionOrBuilder>(
                  transactions_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          transactions_ = null;
        }
        return transactionsBuilder_;
      }

      private com.google.protobuf.ByteString sourcePeerKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes source_peer_key = 2;</code>
       */
      public com.google.protobuf.ByteString getSourcePeerKey() {
        return sourcePeerKey_;
      }
      /**
       * <code>bytes source_peer_key = 2;</code>
       */
      public Builder setSourcePeerKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sourcePeerKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes source_peer_key = 2;</code>
       */
      public Builder clearSourcePeerKey() {
        
        sourcePeerKey_ = getDefaultInstance().getSourcePeerKey();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:iroha.network.transport.MstState)
    }

    // @@protoc_insertion_point(class_scope:iroha.network.transport.MstState)
    private static final iroha.network.transport.Mst.MstState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new iroha.network.transport.Mst.MstState();
    }

    public static iroha.network.transport.Mst.MstState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MstState>
        PARSER = new com.google.protobuf.AbstractParser<MstState>() {
      public MstState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MstState(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MstState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MstState> getParserForType() {
      return PARSER;
    }

    public iroha.network.transport.Mst.MstState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iroha_network_transport_MstState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iroha_network_transport_MstState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tmst.proto\022\027iroha.network.transport\032\021tr" +
      "ansaction.proto\032\033google/protobuf/empty.p" +
      "roto\"V\n\010MstState\0221\n\014transactions\030\001 \003(\0132\033" +
      ".iroha.protocol.Transaction\022\027\n\017source_pe" +
      "er_key\030\002 \001(\0142Z\n\020MstTransportGrpc\022F\n\tSend" +
      "State\022!.iroha.network.transport.MstState" +
      "\032\026.google.protobuf.Emptyb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          iroha.protocol.TransactionOuterClass.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_iroha_network_transport_MstState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_iroha_network_transport_MstState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iroha_network_transport_MstState_descriptor,
        new java.lang.String[] { "Transactions", "SourcePeerKey", });
    iroha.protocol.TransactionOuterClass.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
