/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jp.co.soramitsu.iroha;

public final class BatchType {
  public final static BatchType ATOMIC = new BatchType("ATOMIC", irohaJNI.BatchType_ATOMIC_get());
  public final static BatchType ORDERED = new BatchType("ORDERED", irohaJNI.BatchType_ORDERED_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static BatchType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + BatchType.class + " with value " + swigValue);
  }

  private BatchType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private BatchType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private BatchType(String swigName, BatchType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static BatchType[] swigValues = { ATOMIC, ORDERED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

