/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jp.co.soramitsu.iroha;

public final class Grantable {
  public final static Grantable kAddMySignatory = new Grantable("kAddMySignatory");
  public final static Grantable kRemoveMySignatory = new Grantable("kRemoveMySignatory");
  public final static Grantable kSetMyQuorum = new Grantable("kSetMyQuorum");
  public final static Grantable kSetMyAccountDetail = new Grantable("kSetMyAccountDetail");
  public final static Grantable kTransferMyAssets = new Grantable("kTransferMyAssets");
  public final static Grantable COUNT = new Grantable("COUNT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Grantable swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Grantable.class + " with value " + swigValue);
  }

  private Grantable(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Grantable(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Grantable(String swigName, Grantable swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Grantable[] swigValues = { kAddMySignatory, kRemoveMySignatory, kSetMyQuorum, kSetMyAccountDetail, kTransferMyAssets, COUNT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

