/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jp.co.soramitsu.iroha;

public class iroha {
  public static String toBinaryString(Blob b) {
    return irohaJNI.toBinaryString(Blob.getCPtr(b), b);
  }

  public static Role permissionFor(Grantable arg0) {
    return Role.swigToEnum(irohaJNI.permissionFor(arg0.swigValue()));
  }

  public static boolean isValid(Role perm) {
    return irohaJNI.isValid__SWIG_0(perm.swigValue());
  }

  public static boolean isValid(Grantable perm) {
    return irohaJNI.isValid__SWIG_1(perm.swigValue());
  }

  public static void validateTransaction(ByteVector arg0) {
    irohaJNI.validateTransaction(ByteVector.getCPtr(arg0), arg0);
  }

  public static void validateQuery(ByteVector arg0) {
    irohaJNI.validateQuery(ByteVector.getCPtr(arg0), arg0);
  }

  public static ByteVector signTransaction(ByteVector arg0, Keypair arg1) {
    return new ByteVector(irohaJNI.signTransaction(ByteVector.getCPtr(arg0), arg0, Keypair.getCPtr(arg1), arg1), true);
  }

  public static ByteVector signQuery(ByteVector arg0, Keypair arg1) {
    return new ByteVector(irohaJNI.signQuery(ByteVector.getCPtr(arg0), arg0, Keypair.getCPtr(arg1), arg1), true);
  }

  public static ByteVector hashTransaction(ByteVector arg0) {
    return new ByteVector(irohaJNI.hashTransaction(ByteVector.getCPtr(arg0), arg0), true);
  }

  public static ByteVector hashQuery(ByteVector arg0) {
    return new ByteVector(irohaJNI.hashQuery(ByteVector.getCPtr(arg0), arg0), true);
  }

  public static Hash utxReducedHash(UnsignedTx arg0) {
    return new Hash(irohaJNI.utxReducedHash(UnsignedTx.getCPtr(arg0), arg0), true);
  }

}
