/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jp.co.soramitsu.iroha;

public class ModelQueryBuilder {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ModelQueryBuilder(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ModelQueryBuilder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        irohaJNI.delete_ModelQueryBuilder(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ModelQueryBuilder() {
    this(irohaJNI.new_ModelQueryBuilder(), true);
  }

  public ModelQueryBuilder createdTime(java.math.BigInteger created_time) {
    return new ModelQueryBuilder(irohaJNI.ModelQueryBuilder_createdTime(swigCPtr, this, created_time), true);
  }

  public ModelQueryBuilder creatorAccountId(String creator_account_id) {
    return new ModelQueryBuilder(irohaJNI.ModelQueryBuilder_creatorAccountId(swigCPtr, this, creator_account_id), true);
  }

  public ModelQueryBuilder queryCounter(java.math.BigInteger query_counter) {
    return new ModelQueryBuilder(irohaJNI.ModelQueryBuilder_queryCounter(swigCPtr, this, query_counter), true);
  }

  public ModelQueryBuilder getAccount(String account_id) {
    return new ModelQueryBuilder(irohaJNI.ModelQueryBuilder_getAccount(swigCPtr, this, account_id), true);
  }

  public ModelQueryBuilder getSignatories(String account_id) {
    return new ModelQueryBuilder(irohaJNI.ModelQueryBuilder_getSignatories(swigCPtr, this, account_id), true);
  }

  public ModelQueryBuilder getAccountTransactions(String account_id, int page_size, SWIGTYPE_p_boost__optionalT_shared_model__interface__types__HashType_t first_hash) {
    return new ModelQueryBuilder(irohaJNI.ModelQueryBuilder_getAccountTransactions__SWIG_0(swigCPtr, this, account_id, page_size, SWIGTYPE_p_boost__optionalT_shared_model__interface__types__HashType_t.getCPtr(first_hash)), true);
  }

  public ModelQueryBuilder getAccountTransactions(String account_id, int page_size) {
    return new ModelQueryBuilder(irohaJNI.ModelQueryBuilder_getAccountTransactions__SWIG_1(swigCPtr, this, account_id, page_size), true);
  }

  public ModelQueryBuilder getAccountAssetTransactions(String account_id, String asset_id, int page_size, SWIGTYPE_p_boost__optionalT_shared_model__interface__types__HashType_t first_hash) {
    return new ModelQueryBuilder(irohaJNI.ModelQueryBuilder_getAccountAssetTransactions__SWIG_0(swigCPtr, this, account_id, asset_id, page_size, SWIGTYPE_p_boost__optionalT_shared_model__interface__types__HashType_t.getCPtr(first_hash)), true);
  }

  public ModelQueryBuilder getAccountAssetTransactions(String account_id, String asset_id, int page_size) {
    return new ModelQueryBuilder(irohaJNI.ModelQueryBuilder_getAccountAssetTransactions__SWIG_1(swigCPtr, this, account_id, asset_id, page_size), true);
  }

  public ModelQueryBuilder getAccountAssets(String account_id) {
    return new ModelQueryBuilder(irohaJNI.ModelQueryBuilder_getAccountAssets(swigCPtr, this, account_id), true);
  }

  public ModelQueryBuilder getRoles() {
    return new ModelQueryBuilder(irohaJNI.ModelQueryBuilder_getRoles(swigCPtr, this), true);
  }

  public ModelQueryBuilder getAssetInfo(String asset_id) {
    return new ModelQueryBuilder(irohaJNI.ModelQueryBuilder_getAssetInfo(swigCPtr, this, asset_id), true);
  }

  public ModelQueryBuilder getRolePermissions(String role_id) {
    return new ModelQueryBuilder(irohaJNI.ModelQueryBuilder_getRolePermissions(swigCPtr, this, role_id), true);
  }

  public ModelQueryBuilder getTransactions(HashVector hashes) {
    return new ModelQueryBuilder(irohaJNI.ModelQueryBuilder_getTransactions(swigCPtr, this, HashVector.getCPtr(hashes), hashes), true);
  }

  public ModelQueryBuilder getAccountDetail(String account_id, String key, String writer) {
    return new ModelQueryBuilder(irohaJNI.ModelQueryBuilder_getAccountDetail__SWIG_0(swigCPtr, this, account_id, key, writer), true);
  }

  public ModelQueryBuilder getAccountDetail(String account_id, String key) {
    return new ModelQueryBuilder(irohaJNI.ModelQueryBuilder_getAccountDetail__SWIG_1(swigCPtr, this, account_id, key), true);
  }

  public ModelQueryBuilder getAccountDetail(String account_id) {
    return new ModelQueryBuilder(irohaJNI.ModelQueryBuilder_getAccountDetail__SWIG_2(swigCPtr, this, account_id), true);
  }

  public ModelQueryBuilder getAccountDetail() {
    return new ModelQueryBuilder(irohaJNI.ModelQueryBuilder_getAccountDetail__SWIG_3(swigCPtr, this), true);
  }

  public ModelQueryBuilder getPendingTransactions() {
    return new ModelQueryBuilder(irohaJNI.ModelQueryBuilder_getPendingTransactions(swigCPtr, this), true);
  }

  public UnsignedQuery build() {
    return new UnsignedQuery(irohaJNI.ModelQueryBuilder_build(swigCPtr, this), true);
  }

}
