/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jp.co.soramitsu.iroha;

public class ModelProtoBlocksQuery {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ModelProtoBlocksQuery(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ModelProtoBlocksQuery obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        irohaJNI.delete_ModelProtoBlocksQuery(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ModelProtoBlocksQuery(UnsignedBlockQuery us) {
    this(irohaJNI.new_ModelProtoBlocksQuery(UnsignedBlockQuery.getCPtr(us), us), true);
  }

  public ModelProtoBlocksQuery signAndAddSignature(Keypair keypair) {
    return new ModelProtoBlocksQuery(irohaJNI.ModelProtoBlocksQuery_signAndAddSignature(swigCPtr, this, Keypair.getCPtr(keypair), keypair), true);
  }

  public Blob finish() {
    return new Blob(irohaJNI.ModelProtoBlocksQuery_finish(swigCPtr, this), true);
  }

}
