/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jp.co.soramitsu.iroha;

public class SignatureVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SignatureVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SignatureVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        irohaJNI.delete_SignatureVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SignatureVector() {
    this(irohaJNI.new_SignatureVector__SWIG_0(), true);
  }

  public SignatureVector(long n) {
    this(irohaJNI.new_SignatureVector__SWIG_1(n), true);
  }

  public long size() {
    return irohaJNI.SignatureVector_size(swigCPtr, this);
  }

  public long capacity() {
    return irohaJNI.SignatureVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    irohaJNI.SignatureVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return irohaJNI.SignatureVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    irohaJNI.SignatureVector_clear(swigCPtr, this);
  }

  public void add(Signature x) {
    irohaJNI.SignatureVector_add(swigCPtr, this, Signature.getCPtr(x), x);
  }

  public Signature get(int i) {
    long cPtr = irohaJNI.SignatureVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Signature(cPtr, false);
  }

  public void set(int i, Signature val) {
    irohaJNI.SignatureVector_set(swigCPtr, this, i, Signature.getCPtr(val), val);
  }

}
