/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jp.co.soramitsu.iroha;

public class Signature {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Signature(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Signature obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        irohaJNI.delete_Signature(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PublicKey publicKey() {
    return new PublicKey(irohaJNI.Signature_publicKey(swigCPtr, this), false);
  }

  public Signed signedData() {
    return new Signed(irohaJNI.Signature_signedData(swigCPtr, this), false);
  }

  public boolean equal(Signature rhs) {
    return irohaJNI.Signature_equal(swigCPtr, this, Signature.getCPtr(rhs), rhs);
  }

  public String toString() {
    return irohaJNI.Signature_toString(swigCPtr, this);
  }

}
