/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jp.co.soramitsu.iroha;

public class Transaction {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Transaction(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Transaction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        irohaJNI.delete_Transaction(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Transaction(SWIGTYPE_p_iroha__protocol__Transaction transaction) {
    this(irohaJNI.new_Transaction__SWIG_0(SWIGTYPE_p_iroha__protocol__Transaction.getCPtr(transaction)), true);
  }

  public Transaction(Transaction transaction) {
    this(irohaJNI.new_Transaction__SWIG_2(Transaction.getCPtr(transaction), transaction), true);
  }

  public String creatorAccountId() {
    return irohaJNI.Transaction_creatorAccountId(swigCPtr, this);
  }

  public Blob blob() {
    return new Blob(irohaJNI.Transaction_blob(swigCPtr, this), false);
  }

  public Blob payload() {
    return new Blob(irohaJNI.Transaction_payload(swigCPtr, this), false);
  }

  public Blob reducedPayload() {
    return new Blob(irohaJNI.Transaction_reducedPayload(swigCPtr, this), false);
  }

  public Hash reducedHash() {
    return new Hash(irohaJNI.Transaction_reducedHash(swigCPtr, this), false);
  }

  public boolean addSignature(Signed signed_blob, PublicKey public_key) {
    return irohaJNI.Transaction_addSignature(swigCPtr, this, Signed.getCPtr(signed_blob), signed_blob, PublicKey.getCPtr(public_key), public_key);
  }

  public SWIGTYPE_p_iroha__protocol__Transaction getTransport() {
    return new SWIGTYPE_p_iroha__protocol__Transaction(irohaJNI.Transaction_getTransport(swigCPtr, this), false);
  }

  public java.math.BigInteger createdTime() {
    return irohaJNI.Transaction_createdTime(swigCPtr, this);
  }

  public int quorum() {
    return irohaJNI.Transaction_quorum(swigCPtr, this);
  }

  public SWIGTYPE_p_boost__optionalT_std__shared_ptrT_shared_model__interface__BatchMeta_t_t batchMeta() {
    return new SWIGTYPE_p_boost__optionalT_std__shared_ptrT_shared_model__interface__BatchMeta_t_t(irohaJNI.Transaction_batchMeta(swigCPtr, this), true);
  }

  public SignatureVector signs() {
    return new SignatureVector(irohaJNI.Transaction_signs(swigCPtr, this), true);
  }

}
