/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jp.co.soramitsu.iroha;

public class UnsignedBlockQuery {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected UnsignedBlockQuery(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UnsignedBlockQuery obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        irohaJNI.delete_UnsignedBlockQuery(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UnsignedBlockQuery(BlocksQuery o) {
    this(irohaJNI.new_UnsignedBlockQuery__SWIG_0(BlocksQuery.getCPtr(o), o), true);
  }

  public UnsignedBlockQuery(UnsignedBlockQuery w) {
    this(irohaJNI.new_UnsignedBlockQuery__SWIG_2(UnsignedBlockQuery.getCPtr(w), w), true);
  }

  public UnsignedBlockQuery signAndAddSignature(Keypair keypair) {
    return new UnsignedBlockQuery(irohaJNI.UnsignedBlockQuery_signAndAddSignature(swigCPtr, this, Keypair.getCPtr(keypair), keypair), false);
  }

  public BlocksQuery finish() {
    return new BlocksQuery(irohaJNI.UnsignedBlockQuery_finish(swigCPtr, this), true);
  }

  public Hash hash() {
    return new Hash(irohaJNI.UnsignedBlockQuery_hash(swigCPtr, this), true);
  }

}
